import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://uipxwyxlzfmfogqwpulh.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpcHh3eXhsemZtZm9ncXdwdWxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzY2NTM5NTAsImV4cCI6MTk5MjIyOTk1MH0.Uc_XLP806CZjHcDgg1pQ7g4YIAf00I9IY_0MV5f1Cyc')